name: newsphone_competitions
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.9+14

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.9.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  google_fonts: ^6.3.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  package_info_plus: ^9.0.0
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_analytics: ^12.0.3
  flutter_local_notifications: ^19.4.2
  firebase_auth: ^6.1.2
  http: ^1.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#0072bc"
  image: "assets/android12.png"

  android_12:
    color: "#0072bc"
    image: "assets/android12.png"
    image_dark: "assets/android12.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icon.jpeg"
  min_sdk_android: 21
  remove_alpha_ios: true